project:
  type: website

website:
  title: "Jacob's Blog"
  search: false
  navbar:
    right:
      - icon: arrow-left
        text: back to main website
        href: https://jacobrosenth.al
      # - about.qmd
      - icon: github
        href: https://github.com/jacob-rosenthal
format:
  html:
    theme: sandstone
    css: styles.css
